sudo: false
language: haskell
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - alex-3.1.4
      - happy-1.19.5
      - lib32ncurses5
before_install:
- mkdir -p gcc-arm-embedded
- wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C gcc-arm-embedded
- export PATH="$(echo $PWD/gcc-arm-embedded/*/bin):/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH"
- arm-none-eabi-gcc --version
install:
- git clone https://github.com/galoisinc/ivory
- export IVORY_REPO=$PWD/ivory
- git clone --depth=50 --branch=${TRAVIS_BRANCH} https://github.com/galoisinc/tower
- export TOWER_REPO=$PWD/tower
script:
- make $ENV_TEST_TARGET
ghc:
- 7.8
env:
- ENV_TEST_TARGET=ivory-freertos-bindings
- ENV_TEST_TARGET=ivory-bsp-stm32
- ENV_TEST_TARGET=tower-freertos-stm32
- ENV_TEST_TARGET=tower-freertos-stm32-tests
- ENV_TEST_TARGET=ivory-bsp-tests
notifications:
  slack:
    secure: HV4BpAHw/LibvN0LRLJIZkhAtFWr77FnG9z2+u4TWXIwdkcTzFw+zB7S3AvzY0PpF9Y77/9/tQlipm+frV2fYk+2+zNYZnBYiPvgfu10JJql8B1jifiymBFXPOqYahJk9irApf0CAzdDj6eFUH/YX480eV4Xpnw+WcPiig5WBpg=
    secure: A2JXPOP11K/4praaswuJ17zcXLo1SsF/WBZ5sO+c18scjAKCLeQuci1xUDUCZXspeDGfnJq0hlz95qbISu7LtoK55zQPt0l/4P0es7x34paSrEs5Ca8lXK5qim2ozfvb6TIeuYLnS/Asj3fFQmuUlbWwkxlt3pcJFi0wxaJjt8o=
