language: haskell
before_install:
  - sudo add-apt-repository "deb http://mirrors.kernel.org/ubuntu/ trusty main universe"
  - sudo apt-get install gcc-arm-none-eabi
  - sudo apt-get install -f
  - uname -a
  - which arm-none-eabi-gcc
  - which arm-none-eabi-ld
  - ls -l gcc-arm-none-eabi-4_8-2014q3/bin/
  - arm-none-eabi-gcc --version
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
  - git clone --branch tower-9 https://github.com/galoisinc/tower
  - export TOWER_REPO=$PWD/tower
install:
  - cabal install alex
  - cabal install happy
script:
  - echo $PATH
  - ls -l gcc-arm-none-eabi-4_8-2014q3/bin/
  - which arm-none-eabi-gcc
  - arm-none-eabi-gcc --version
  - IVORY_REPO=$IVORY_REPO TOWER_REPO=$TOWER_REPO make
ghc:
  - 7.6.3
  - 7.8.3

