language: haskell
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - alex-3.1.4
      - happy-1.19.5
before_install:
- export PATH="/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH"
install:
- sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
- sudo apt-get update -qq
- sudo apt-get install -y gcc-arm-none-eabi
- uname -a
- which arm-none-eabi-gcc
- which arm-none-eabi-ld
- arm-none-eabi-gcc --version
- git clone https://github.com/galoisinc/ivory
- export IVORY_REPO=$PWD/ivory
- git clone https://github.com/galoisinc/tower
- export TOWER_REPO=$PWD/tower
script:
- echo $PATH
- which arm-none-eabi-gcc
- arm-none-eabi-gcc --version
- make $ENV_TEST_TARGET
ghc:
- 7.8
env:
- ENV_TEST_TARGET=ivory-freertos-bindings
- ENV_TEST_TARGET=ivory-bsp-stm32
- ENV_TEST_TARGET=tower-freertos-stm32
- ENV_TEST_TARGET=tower-freertos-stm32-tests
- ENV_TEST_TARGET=ivory-bsp-tests
notifications:
  slack:
    secure: HV4BpAHw/LibvN0LRLJIZkhAtFWr77FnG9z2+u4TWXIwdkcTzFw+zB7S3AvzY0PpF9Y77/9/tQlipm+frV2fYk+2+zNYZnBYiPvgfu10JJql8B1jifiymBFXPOqYahJk9irApf0CAzdDj6eFUH/YX480eV4Xpnw+WcPiig5WBpg=
    secure: A2JXPOP11K/4praaswuJ17zcXLo1SsF/WBZ5sO+c18scjAKCLeQuci1xUDUCZXspeDGfnJq0hlz95qbISu7LtoK55zQPt0l/4P0es7x34paSrEs5Ca8lXK5qim2ozfvb6TIeuYLnS/Asj3fFQmuUlbWwkxlt3pcJFi0wxaJjt8o=
