language: haskell
before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi
  - uname -a
  - which arm-none-eabi-gcc
  - which arm-none-eabi-ld
  - arm-none-eabi-gcc --version
  - git clone https://github.com/galoisinc/ivory
  - export IVORY_REPO=$PWD/ivory
  - git clone --branch tower-9 https://github.com/galoisinc/tower
  - export TOWER_REPO=$PWD/tower
install:
  - cabal install alex
  - cabal install happy
script:
  - echo $PATH
  - which arm-none-eabi-gcc
  - arm-none-eabi-gcc --version
  - IVORY_REPO=$IVORY_REPO TOWER_REPO=$TOWER_REPO make $ENV_TEST_TARGET
ghc:
  - 7.6.3
  - 7.8.3
env:
  - ENV_TEST_TARGET=ivory-freertos-bindings
  - ENV_TEST_TARGET=ivory-bsp-stm32
  - ENV_TEST_TARGET=tower-freertos-stm32
  - ENV_TEST_TARGET=tower-freertos-stm32-tests
  - ENV_TEST_TARGET=ivory-bsp-tests
